---
services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    image: ghcr.io/fish895623/custom-jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
version: "3.9"
volumes:
  jenkins_home: null
